publish:
  stage: publish
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
  extends: [ .sbt ]
  variables:
    GIT_STRATEGY: clone
    GIT_DEPTH: 0 # Full clone for sbt-dynver
  script:
  - |
    git config --global --add safe.directory $CI_PROJECT_DIR
    if [[ "${CI_COMMIT_BRANCH:-false}" != "false" ]]; then
      git checkout -b $CI_COMMIT_BRANCH
    elif [[ "${CI_COMMIT_TAG:-false}" != "false" ]]; then
      git checkout -b $CI_COMMIT_TAG
    fi
  - sbt "show version" ci-release
